config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'home/about'

  get 'home/contact'

  get 'home/faq'

  get 'home/pricing'

  get 'home/features'

  resources :invoices

  root  to: 'invoices#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/invoice_search.rb
class InvoiceSearch
  attr_reader :date_from, :date_to
  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end
  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end
  private
    def parsed_date(date_str, default)
      Date.parse(date_str)
    rescue ArgumentError, TypeError
      default
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def pricing
  end

  def features
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :salesperson)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/home/about.html.haml
%h1 Home#about
%p Find me in app/views/home/about.html.haml

app/views/home/contact.html.haml
%h1 Home#contact
%p Find me in app/views/home/contact.html.haml

app/views/home/faq.html.haml
%h1 Home#faq
%p Find me in app/views/home/faq.html.haml

app/views/home/features.html.haml
%h1 Home#features
%p Find me in app/views/home/features.html.haml

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/home/pricing.html.haml
%h1 Home#pricing
%p Find me in app/views/home/pricing.html.haml

app/views/invoices/_form.html.haml
= form_for(@invoice) do |f|
  - if @invoice.errors.any?
    #error_explanation
      %h2
        = pluralize(@invoice.errors.count, "error")
        prohibited this invoice from being saved:
      %ul
        - @invoice.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :date
    %br/
    = f.datetime_select :date
  .field
    = f.label :company
    %br/
    = f.text_field :company
  .field
    = f.label :tax
    %br/
    = f.text_field :tax
  .field
    = f.label :salesperson
    %br/
    = f.text_field :salesperson
  .actions
    = f.submit

app/views/invoices/edit.html.haml
%h1 Editing Invoice
= render 'form'
= link_to 'Show', @invoice
|
= link_to 'Back', invoices_path

app/views/invoices/index.html.haml
%p#notice= notice
%h1.page-header Listing Invoices

.row
  .pull-right
    = form_tag invoices_path, method: :get do
      = text_field_tag 'search[date_from]', @search.date_from
      = text_field_tag 'search[date_to]', @search.date_to
      = submit_tag 'Search', class: 'btn search-button'
.row
  .col.col-sm-12
    %table.table.table-hover.table-striped
      %thead
        %tr
          %th Date
          %th Company
          %th Tax
          %th Salesperson
          %th{colspan: '3'}
      %tbody
        - @invoices.each do |invoice|
          %tr
            %td= invoice.date.strftime('%m/%d/%Y')
            %td= invoice.company
            %td= invoice.tax
            %td= invoice.salesperson
            %td= link_to 'Show', invoice, class: 'btn btn-block btn-default'
            %td= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-block btn-success'
            %td= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-block btn-danger'
    %br/
    = link_to 'New Invoice', new_invoice_path

app/views/invoices/new.html.haml
%h1 New Invoice
= render 'form'
= link_to 'Back', invoices_path

app/views/invoices/show.html.haml
%p#notice= notice
%p
  %strong Date:
  = @invoice.date
%p
  %strong Company:
  = @invoice.company
%p
  %strong Tax:
  = @invoice.tax
%p
  %strong Salesperson:
  = @invoice.salesperson
= link_to 'Edit', edit_invoice_path(@invoice)
|
= link_to 'Back', invoices_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', http_equiv: 'Content-Type'}/
    %title Entapp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li
          = link_to 'Home', root_path
        %li
          = link_to 'About Us', home_about_path
        %li
          = link_to 'Contact', home_contact_path
        %li
          = link_to 'FAQ', home_faq_path
        %li
          = link_to 'Pricing', home_pricing_path
        %li
          = link_to 'Invoices', invoices_path
        - if current_user
          %li
            = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path
      %br
      .row
        .col-sm-12
        - flash.each do |key,value|
          %div{class: "fade in alert alert-#{key}"}
            = value
            %a.close{'data-dismiss' => 'alert', href: '#', 'aria-hidden' => 'true'}
              &times;

      = yield